### ISSUE TITLE
Package release

### ISSUE THREAD

**Issue by achim-k** [ros-misc-utilities/ffmpeg_image_transport#16]
Hi!

Thanks for creating this package, it is super helpful. 
Are you planning to release it for `humble`, `iron`, ... anytime soon?

**Comment by berndpfrommer** [comment]
https://github.com/ros-perception/image_transport_plugins/issues/158

**Comment by berndpfrommer** [comment]
Package has been release to humble, iron, and rolling.
Will take a while until the distro maintainers will sync, but the package should be available soon.
